### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by nicklucius** [Chicago/tnp-reporting-manual#14]
The link to the BACP Rule on the overview page is broken. Here is the link:

https://www.cityofchicago.org/content/dam/city/depts/dol/rulesandregs/TNPRulesFinalEFF20151120.pdf

**Comment by levyj** [comment]
https://www.cityofchicago.org/city/en/depts/bacp/supp_info/transportation-network-providers.html links to https://www.cityofchicago.org/content/dam/city/depts/bacp/rulesandregs/TNPRulesAmendedeffJan12017.pdf. However, that seems to be more than just 2.02 so I am going to check with BACP to make sure we change this correctly.

Thanks.

**Comment by levyj** [comment]
I did not get a direct reply from BACP but after looking again, myself, I think that link makes sense to use.
