### ISSUE TITLE
Outdated link

### ISSUE THREAD

**Issue by nicklucius** [Chicago/tnp-reporting-manual#15]
The link to the municipal code on the Overview section is out of date. There is a banner at chicagocode.org that states explains.

https://chicagocode.org/9/9-115/

**Comment by levyj** [comment]
Yes. Unfortunately, Am Legal is terrible. As far as I know, there is no stable link to a particular section of the code.

I will ask BACP if there is some better link we can use.

Thanks!

**Comment by levyj** [comment]
There wasn't a stable Am Legal link so I used http://library.amlegal.com/nxt/gateway.dll/Illinois/chicago_il/municipalcodeofchicago?f=templates$fn=default.htm$3.0$vid=amlegal:chicago_il and people will have to drill down.

**Comment by nicklucius** [comment]
I found a way to link to Am Legal:  
http://library.amlegal.com/nxt/gateway.dll/Illinois/chicago_il/title9vehiclestrafficandrailtransportati/chapter9-115transportationnetworkprovide?f=templates$fn=default.htm$3.0$vid=amlegal:chicago_il$anc=JD_Ch.9-115

I'm reopening and will open a pull request for @levyj to review.

**Comment by levyj** [comment]
Thanks for figuring that out, @nicklucius!
