### ISSUE TITLE
Outdated link to BACP rules

### ISSUE THREAD

**Issue by nicklucius** [Chicago/tnp-reporting-manual#27]
Looks like it's directing users to a 2017 version of the TNP rules, rather than the must recent ones from 2020. Should be: https://www.chicago.gov/content/dam/city/depts/dol/rulesandregs/TNPRulesAmendedeff81020.pdf

@levyj is this something you can do?

**Comment by nicklucius** [comment]
Reopening because I think it still needs to be fixed on https://github.com/Chicago/tnp-reporting-manual/blob/gh-pages/index.md

**Comment by levyj** [comment]
Good catch. Thanks!
