### ISSUE TITLE
TNP Reporting Manual.xlsx produces an error when attempting to open in Excel

### ISSUE THREAD

**Issue by levyj** [Chicago/tnp-reporting-manual#9]

**Comment by tomschenkjr** [comment]
@levyj - I went back to explore [previous releases](https://github.com/Chicago/tnp-reporting-manual/releases) and it appears that the XLSX file was corrupted awhile ago. I haven't been able to successfully download and open prior files before this.

We can reconstruct the file or just go with the webpage at this point. Preference?

**Comment by levyj** [comment]
@tomschenkjr - I think a downloadable, machine-readable file (not necessarily Excel) has value, both on principle and potentially as a practical matter in reducing the chances of a TNP making a mistake. However, everything is a trade-off so I don't know that it is worth a ton of effort -- at least until someone asks.

**Comment by tomschenkjr** [comment]
Do you have a local file that seems to open?

**Comment by levyj** [comment]
Probably not an up-to-date one, if any file at all.

I may just have changed my mind. To see what would happen, I just did a copy/paste from one of the requirements file tables to a text editor and got a clean, tab-separated file. If it is truly that simple, maintaining a download file may not be worth it.

**Comment by tomschenkjr** [comment]
This is true. Also, if you're in IE, you can right-click on the table and export to Excel.

**Comment by levyj** [comment]
Ok. I just marked this `wontfix`. When I get a chance, I will remove the download link and close the issue.
